version: "3.9"

services:
  app:
    build: .
    container_name: apply-tracker-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src        # solo monta src para hot reload
      - ./prisma:/app/prisma  # y prisma si lo necesitas en dev
    environment:
      - IS_DOCKER=true
    command: sh -c "pnpm dlx prisma migrate deploy && pnpm run dev"